In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
df0 = pd.read_csv("dataset (1).csv", header=None )
df1 = pd.read_csv("dataset (2).csv", header=None )
df2 = pd.read_csv("dataset (3).csv", header=None )
df3 = pd.read_csv("dataset (4).csv", header=None )

df = pd.concat([df0,df1,df2,df3], axis = 0)

In [3]:
x = df.loc[:,0:63]
y = df[64]

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [5]:
sc = StandardScaler()
x_train = pd.DataFrame(sc.fit_transform(x_train))
x_test = pd.DataFrame(sc.transform(x_test))

In [6]:
lr_grid = {'max_depth' : [4,8,16,32,64,128],
           'criterion' : ['entropy','gini']}

clf = RandomForestClassifier(n_estimators=100, max_features='sqrt', random_state=42)

gs = GridSearchCV(estimator = clf, param_grid=lr_grid,cv = 5)
gs.fit(x_train,y_train)
y_pred = gs.predict(x_test)
gs.best_params_

{'criterion': 'entropy', 'max_depth': 64}

In [7]:
print('Classification Report: \n', classification_report(y_test,y_pred))

Classification Report: 
               precision    recall  f1-score   support

           0       0.94      0.98      0.96       719
           1       0.94      0.92      0.93       693
           2       0.92      0.94      0.93       732
           3       0.89      0.86      0.87       776

    accuracy                           0.92      2920
   macro avg       0.92      0.92      0.92      2920
weighted avg       0.92      0.92      0.92      2920



In [8]:
print('Confusion Matrix: \n', confusion_matrix(y_test,y_pred))

Confusion Matrix: 
 [[703   0   4  12]
 [  0 638  10  45]
 [ 10  11 685  26]
 [ 32  32  45 667]]
